name: Next.js Build and Deploy

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Set this to the node version you are using

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./web  # Set this to the path of your Next.js project if different
      run: npm install --force

    - name: Build
      working-directory: ./web  # Set this to the path of your Next.js project if different
      run: npm run build

    - name: Deploy
      working-directory: ./web  # Set this to the path of your Next.js project if different
      run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
